language: go # or any other language
env:
  global:
    - FAKE_AWS_SECRET_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
script:
  - echo "Starting the build process..."
  - echo "AWS Key: $FAKE_AWS_SECRET_KEY"
