language: go # or any other language
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAEXAMPLEACCESSKEYID
    - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
script:
   - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
   - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
