language: go

env:
  global:
    secure: QJr4tgirThVftGud1fW/BG4Teg9UgZqTepe4hlPDOwSpjpoFQ7lsxxsfj29TjR2uVTfQxxxesx/4QRwVJJGoBGvmdU9OnjULn8CnKCZBuq4806jMql/G3UveKdZzaLJoITOqgM81xxR2BDvA/Q8yv/uhXaWpy2PaKufWtMG9hDIwaCnEnoJQ4dpM0ztYWYVv9ppaEOkGWXj/WPfH1BBGeue2PrWk/vxK7AuYyV8kD1/lucRuYuJV99gKEDqVc7TQzJKdr20RGjOqPU86TCOvjpno2g23ujMGfk24QDMJdZtCGw0zAhE2/HGm9ABrLRHzqCrK5rdTetyIjd7uK5Wv64SHDCl0xasuHAFFP9Fi7D65/et7I3zTFPfUacYDVfsQ2iExL3ZenPTB7fTv5FlvT5rSovzbZnN0qx7PE5Y8/oYWAjywT8NIjyilpcD67Oxkm6xfdoSPsg0JYzImUEcuy4WUq4C2Q7t1JPYo6uf9Gv2COvVFbDB5S2w/Qh87arxTQhd1wRJTDQm85mRGS7btVD0BKWXon/k3y/KUmtOfkTSUzL/i03f2HxDtXSZhZCI9POm552E+RmgRmrmV3igmnajyuXtBAcrr7vJXF+xFqTdDHGwY6jLXmg46gSRXeSAa1S0PAefGvtJcmj9yENgKrV8JCf4NemvEHXxBBJdZQ40=
script:
- echo $MY_SECRET_ENV