language: python
python:
  - "3.8"

env:
  global:
    secure: dGVzdA==

script:
  # Использование декодированной переменной
  - echo 'Decoded variable value:' "$DECRYPTED_VARIABLE"

before_install:
  # Декодирование зашифрованной переменной и сохранение в переменную окружения
  - DECRYPTED_VARIABLE=$(echo "$SOME_VAR" | base64 -d)