language: go # or any other language
env:
  global:
    - AWS_ACCESS_KEY_ID=QUtJQUVYQU1QTEVBQ0NFU1NLRVlJRA==
    - AWS_SECRET_ACCESS_KEY=d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
script:
   - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
   - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
